version: "3.8"

services:
  # フロントエンドサービス（Angular）
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["ng", "serve", "--host", "0.0.0.0"]
    depends_on:
      - backend

  # バックエンドサービス（Laravel）
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:random-generated-key
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: my_database
      DB_USERNAME: user
      DB_PASSWORD: password
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    depends_on:
      - db

  # データベースサービス（MySQL）
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data:
